"""Perform a lightweight end-to-end sanity check of training artifacts and inference."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pandas as pd

from src.inference.predictor import load_model, predict_dataframe


def main() -> None:
    run_dir = Path("runs/run_001")
    model_path = run_dir / "model.joblib"

    # Auto-train on first run so smoke tests can run in fresh clones.
    if not model_path.exists():
        print("No trained model found. Running training first...")
        subprocess.run(
            [sys.executable, "train.py", "--config", "configs/train/default.yaml"],
            check=True,
        )

    holdout_path = run_dir / "holdout.csv"
    if not holdout_path.exists():
        raise FileNotFoundError("Smoke test requires holdout.csv generated by training")

    df = pd.read_csv(holdout_path)
    # Keep the check fast by scoring only a tiny sample.
    X = df.drop(columns=["target"], errors="ignore").head(5)

    model = load_model(run_dir)
    pred_df = predict_dataframe(model, X)

    assert not pred_df.empty, "Predictions are empty"
    assert "prediction" in pred_df.columns, "Missing prediction column"
    print("Smoke test passed. Predictions shape:", pred_df.shape)


if __name__ == "__main__":
    main()
